"""new fields in user model

Revision ID: 077073f6b798
Revises: 5a52bff0cadc
Create Date: 2025-05-08 14:46:40.750350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077073f6b798'
down_revision = '5a52bff0cadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
